### ISSUE TITLE
Text Chat is missing when having meetings

### ISSUE THREAD

**Issue by mlippert** [rifflearning/riff-rtc#115]
## Description

The Text Chat Icon (and text chat itself) is missing when having a Riff meeting. Notice from the screenshot that the text chat icon which is expected in the bottom right corner isn't there.

### Steps to Reproduce

1. Go to https://staging.riffplatform.com
1. Join a meeting w/ at least 1 other person (Click on Chat, enter room and display name...)
1. See (or don't see) missing text chat icon

### Screenshots
![image](https://user-images.githubusercontent.com/2589356/58819742-e44dc480-85fe-11e9-8136-78b1ec69f525.png)

### Site the bug occurred on:
[staging](https://staging.riffplatform.com) running riff-rtc ver `1.2.0-dev.7`

**Comment by adonahue** [comment]
Verified.
