### ISSUE TITLE
Create aggregate Riff activity data report for GT

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-rtc#122]
The Grant Thornton teams have had a low level of activity in the Riff Platform, but not none. This task is to pull data from the GT node and aggregate it into a report. Mike will do a database dump; Jordan will process the data into something coherent; Beth will put together the report.

**Comment by mlippert** [comment]
The backup of the grantthornton riffdata database as of today is complete: [mongodb_riff-test.pfm.grantthornton.backup-20190610140928.gz](https://drive.google.com/file/d/1uS79V77Fyg9dohptAcAhi7_V3bvE8r82/view?usp=sharing) in my Google drive [AWS backups](https://drive.google.com/drive/folders/1_dYCHsqXDxGDOn9MuuKjFhSUvhfWWBPW?usp=sharing) folder

**Comment by adonahue** [comment]
@jordanreedie - this is done from a dev standpoint yes? @ebporter - can I close this out from the board?
