### ISSUE TITLE
Refactoring for style

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-rtc#71]
This is a story about making the code in Riff RTC more or less conform to a certain style (ESLint) in order to improve maintainability and allow the code to be "linted" or checked for style inconsistencies. This is a story that is not ever really completely done, but this is a first effort, involving getting the ESLint config in place.

**Comment by adonahue** [comment]
This story is mostly done in terms of having chosen a code style and structure to conform to that style, check it and report when we don't match. 

Once Jordan does his style clean up, there will be a small amount of configuration work to "finish" this story.
