### ISSUE TITLE
Toggle Meeting Mediator (Riff Video)

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-rtc#75]
This is a trivial piece of work once the video chat is refactored. This card is on the board to track this specific task, which is just making the MM "toggle-able" in the video code, but not any of the other business logic to decide when or under what conditions the MM should be toggled.

**Comment by adonahue** [comment]
@ebporter - is this tied to the NEXT Canada Cohort 2 milestone?

**Comment by juliariffgit** [comment]
Technically done, but not ready for review until the rest of the refactoring is done.

**Comment by ebporter** [comment]
This issue should be moved along... the testable and reviewable manifestation of this feature will happen via another task (s).
