### ISSUE TITLE
Dashboard: Refactoring for style

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-rtc#78]
This is half of the Dashboard refactoring story (tackling the mono-blobs of code) that focuses on style. 

Goals for 4/29 Sprint
- Pull updated code from EDU and re-incorporate into platform code.  Refactored code for all of dashboard, but still with some (introduced) bugs. But basically, have cleaned up code that can be worked on by anybody.

Goals for (5/13) sprint:

- Clean up code for bugs style and have a working version that is fully refactored. Be ready to start Phase 2, the packaging.

**Comment by juliariffgit** [comment]
Had to work on Zenhub for most of yesterday, but has begun work. Doesn't think there are any blockers atm. Working on influence chart.

**Comment by juliariffgit** [comment]
Made some progress. Style almost considered done - may need to fix the Gantt chart for resizing issues. Some small styling issues will be addressed once modularity work begins.

**Comment by ebporter** [comment]
This issue is closed.
