### ISSUE TITLE
Stage 1: Refactoring

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-rtc#81]
This is an Epic that captures all the work involved in Stage 1 of the Riff-Rtc Refactoring effort. The effort consists of tackling and improving the flow and readability (as well as making the code adhere to our style standards) of two big components (chat and dashboard). The refactoring effort will result in cleaner, more well segmented code, but no changes in functionality.

**Comment by adonahue** [comment]
@juliariffgit - I think this epic can be "closed". Not sure how you want to do that for reporting and tracking. LMK so I can do the same w. other epics. Thanks!

**Comment by juliariffgit** [comment]
@adonahue, I think we're safe to "Close and Comment" on these epics. They will not have PRs associated directly to them, so closing this way should not have that "detach" effect we see when closing stories. I'll do that for this one, and you can do the same for any other epics.
