### ISSUE TITLE
Dashboard: Refactoring for modularity

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-rtc#83]
This is half of the Dashboard refactoring story (tackling the mono-blobs of code) that focuses on modularizing.

Goals for 4/29 Sprint

Pull updated code from EDU and re-incorporate into platform code. Refactored code for all of dashboard, but still with some (introduced) bugs. But basically, have cleaned up code that can be worked on by anybody.
Goals for (5/13) sprint:

Clean up code for bugs style and have a working version that is fully refactored. Be ready to start Phase 2, the packaging.

**Comment by juliariffgit** [comment]
Started work on this now that styling is mostly done.

Completed part 1 already (rifflearning/riff-rtc#103)

**Comment by juliariffgit** [comment]
Opened a second PR on this one, but not merged yet.  Refactoring dashboard actions + clean-up. Found a few bugs while working.

**Comment by adonahue** [comment]
@mlippert - is there anything to Review or QA on this story? Can it get closed? Thx!

**Comment by mlippert** [comment]
The only review I'd expect is checking that everything continues to work the same as it did before this was merged.

However since there is a follow-on story that is currently in code review, I'd say you might as well move this one along,
